#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.89e+21,'cm^5/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 1,
    label = "X + X + NH3 <=> HX + N[Pt]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.048, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 2,
    label = "X + NH3 <=> [Pt].N",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.025, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 1 X + H3N <=> H3NX in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 1 X + H3N <=> H3NX in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 3,
    label = "X + [Pt].N <=> HX + N[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3.46e+20,'cm^2/(mol*s)'), n=0, Ea=(93,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 35 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 35 X_4 + NH3_X <=> NH2_X + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
facet: None
site: None
""",
)

entry(
    index = 4,
    label = "X + N[Pt] <=> HX + N=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.01e+21,'cm^2/(mol*s)'), n=0, Ea=(110,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 49 Ni_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H2;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 49 Ni_4 + NH2_X <=> NHX_1 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H2;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 5,
    label = "N=[Pt] + [Pt].N <=> N[Pt] + N[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.557e+21,'cm^2/(mol*s)'), n=0, Ea=(55.964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;Adsorbate1] for rate rule [N-R;*=NH]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;Adsorbate1] for rate rule [N-R;*=NH]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 6,
    label = "OX + HX <=> X + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 7,
    label = "X + X + H2O <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(62.3389,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 62.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 62.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 8,
    label = "OX + N[Pt] <=> HOX + N=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.784e+21,'cm^2/(mol*s)'), n=0, Ea=(139911,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 40 H2NX + O* <=> OH* + HNX in Surface_Abstraction/training
    This reaction matched rate rule [O;*-N-H]
    family: Surface_Abstraction
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 40 H2NX + O* <=> OH* + HNX in Surface_Abstraction/training
This reaction matched rate rule [O;*-N-H]
family: Surface_Abstraction
metal: None
facet: None
site: None
""",
)

entry(
    index = 9,
    label = "OX + [Pt].N <=> HOX + N[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.557e+21,'cm^2/(mol*s)'), n=0, Ea=(59601.3,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 47 O* + H3NX <=> H2NX + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [N-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None
    facet: None
    site: None
    Ea raised from 56.0 to 59.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 47 O* + H3NX <=> H2NX + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [N-R;*=O]
family: Surface_Abstraction_vdW
metal: None
facet: None
site: None
Ea raised from 56.0 to 59.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 10,
    label = "X + H2O <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 11,
    label = "OX + H2OX <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(43100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 12,
    label = "HX + HOX <=> X + H2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 13,
    label = "N=[Pt] + H2OX <=> HOX + N[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.17313e+12,'m^2/(mol*s)'), n=1.13551, Ea=(145.878,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=NH]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*=NH]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 14,
    label = "X + N=[Pt] <=> N#[Pt] + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.9e+21,'cm^2/(mol*s)'), n=0, Ea=(118,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 50 Ni_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [N-H;VacantSite]
    family: Surface_Dissociation
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 50 Ni_4 + NHX_2 <=> NX + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [N-H;VacantSite]
family: Surface_Dissociation
metal: None
facet: None
site: None
""",
)

entry(
    index = 15,
    label = "OX + N=[Pt] <=> N#[Pt] + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.291e+21,'cm^2/(mol*s)'), n=0, Ea=(45350,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 41 HNX-2 + O* <=> OH* + NX in Surface_Abstraction/training
    This reaction matched rate rule [O;*=N-H]
    family: Surface_Abstraction
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 41 HNX-2 + O* <=> OH* + NX in Surface_Abstraction/training
This reaction matched rate rule [O;*=N-H]
family: Surface_Abstraction
metal: None
facet: None
site: None
""",
)

entry(
    index = 16,
    label = "N#[Pt] + [Pt].N <=> N=[Pt] + N[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.557e+21,'cm^2/(mol*s)'), n=0, Ea=(55.964,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [N-R;Adsorbate1] for rate rule [N-R;*#N]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [N-R;Adsorbate1] for rate rule [N-R;*#N]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 17,
    label = "N#[Pt] + N[Pt] <=> N=[Pt] + N=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.784e+21,'cm^2/(mol*s)'), n=0, Ea=(139.911,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;*-N-H] for rate rule [:N#*;*-N-H]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 18,
    label = "N#[Pt] + H2OX <=> HOX + N=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.17313e+12,'m^2/(mol*s)'), n=1.13551, Ea=(145.878,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#N]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;Adsorbate1] for rate rule [O-R;*#N]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 19,
    label = "[Pt]ON=[Pt] <=> OX + N#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 20,
    label = "X + NO <=> [Pt]N=O",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.019, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 49 Pt + NO <=> NO_X in Surface_Adsorption_Single/training
    This reaction matched rate rule [N=O;VacantSite]
    family: Surface_Adsorption_Single
    metal: None
    facet: None
    site: None"""),
    longDesc = 
"""
Matched reaction 49 Pt + NO <=> NO_X in Surface_Adsorption_Single/training
This reaction matched rate rule [N=O;VacantSite]
family: Surface_Adsorption_Single
metal: None
facet: None
site: None
""",
)

entry(
    index = 21,
    label = "X + [Pt]N=O <=> [Pt]ON=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.27e+15,'m^2/(mol*s)'), n=0.549, Ea=(20.6727,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_DoubleBond_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 22,
    label = "X + X + N2 <=> [Pt]N=N[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Bidentate
""",
)

entry(
    index = 23,
    label = "[Pt]N=N[Pt] <=> N#[Pt] + N#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(182.597,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation
    Ea raised from 0.0 to 182.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
Ea raised from 0.0 to 182.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 24,
    label = "N#[Pt] + [Pt]ON=[Pt] <=> OX + [Pt]N=N[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.04965e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(52.7481,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*-O-N]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
""",
)

entry(
    index = 25,
    label = "X + N2 <=> N#N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.025, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 1 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 1 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 26,
    label = "X + N#N.[Pt] <=> [Pt]N=N[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_vdW_to_Bidentate"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_vdW_to_Bidentate
""",
)

entry(
    index = 27,
    label = "NO + NO <=> ONNO_cis",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.1562e+30,'m^3/(mol*s)'), n=-7.48856, Ea=(5.63876,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.354218852058, var=34.8187486739, Tref=1000.0, N=6, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
        Total Standard Deviation in ln(k): 12.7194203157
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
    Total Standard Deviation in ln(k): 12.7194203157
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 28,
    label = "X + X + ONNO_cis <=> [Pt]N=O + [Pt]N=O",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [N;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 29,
    label = "[Pt]OO[Pt] <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.96e+10,'1/s'), n=0.422, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined]
    Euclidian distance = 0
    family: Surface_Bidentate_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 30,
    label = "[Pt]OO[Pt] + N#[Pt] <=> OX + [Pt]ON=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(6.09931e+17,'m^2/(mol*s)'), n=-0.0171111, Ea=(52.7481,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [:N#*;*R-O]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [:N#*;*R-O]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 31,
    label = "O2 + NO <=> ONOOJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(117000,'m^3/(mol*s)','*|/',-1), n=0, Ea=(51.7084,'kJ/mol','+|-',-0.001), T0=(1,'K'), Tmin=(473,'K'), Tmax=(703,'K'), Pmin=(1333,'Pa'), Pmax=(33600,'Pa'), comment="""Matched reaction 5 NO + O2 <=> NO3 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_N-3R!H-u0_Ext-1N-R]
    family: R_Recombination
    Ea raised from 13.4 to 51.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 5 NO + O2 <=> NO3 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_N-3R!H-u0_Ext-1N-R]
family: R_Recombination
Ea raised from 13.4 to 51.7 kJ/mol to match endothermicity of reaction.
""",
)

